### ISSUE TITLE
django.db.utils.IntegrityError: null value in column "name" of relation "django_content_type" violates not-null constraint

### ISSUE THREAD

**Issue by benjacque** [syqu22/django-react-blog#3]
Quite a lot of issues, for instance:
 - "utils.py", line 89, in _execute return self.cursor.execute(sql, params); 
- return self.cursor.execute(sql, params) django.db.utils.ProgrammingError: relation "auth_group" does not exist; 
- return self.cursor.execute(sql, params) django.db.utils.ProgrammingError: relation "users_user" does not exist; 
- django.db.utils IntegrityError: null value in column "name" of relation "django_content_type" violates not-null constraint. 

One day spent on implementing it, but without any result.

**Comment by syqu22** [comment]
Hello. Sorry for the late respones but apparently the problem was that Django needs folder named "migrations" in every app directory for migration process, so I did removed it from gitignore blacklist. Everything should now works with a fresh database.
